---
# tasks file for setup-shell

- name: Force a color prompt
  lineinfile:
    path: /root/.bashrc
    insertafter: "^#force_color_prompt=.*$"
    line: "force_color_prompt=yes"

- name: Make root color prompt red (so you know it's root)
  replace:
    path: /root/.bashrc
    regexp: "32m"
    replace: "31m"

- name: Source additional configurations in bashrc
  lineinfile:
    path: /root/.bashrc
    line: "source /root/.bashrc_extra"

- name: Copy rc files
  copy:
    src: files/
    dest: /root/

- name: Make diff-highlight available for git
  copy:
    src: /usr/share/doc/git/contrib/diff-highlight/diff-highlight
    dest: /usr/local/bin/diff-highlight
    remote_src: yes
    mode: a+x
