---
# tasks file for setup-smr

- name: Checkout git repository 'smrealms/dockerize'
  git:
    repo: https://github.com/smrealms/dockerize.git
    dest: /root/dockerize

- name: Copy and decrypt .env file
  copy:
    src: files/env.secrets
    dest: /root/dockerize/.env
