---
# tasks file for setup-smr

- name: Force a color prompt
  lineinfile:
    path: /root/.bashrc
    insertafter: "^#force_color_prompt=.*$"
    line: "force_color_prompt=yes"

- name: Make root color prompt red (so you know it's root)
  replace:
    path: /root/.bashrc
    regexp: "32m"
    replace: "31m"

- name: Change default 'll' alias
  lineinfile:
    path: /root/.bashrc
    regexp: "^alias ll=.*$"
    line: "alias ll='ls -CF'"

- name: Change default 'l' alias
  lineinfile:
    path: /root/.bashrc
    regexp: "^alias l=.*$"
    line: "alias l='ls -alF'"

- name: Add alias for docker-compose
  lineinfile:
    path: /root/.bash_aliases
    line: "alias dc='docker-compose'"
    create: yes

- name: Checkout git repository 'smrealms/dockerize'
  git:
    repo: https://github.com/smrealms/dockerize.git
    dest: "{{ smr_home_dir }}"

- name: Create acme.json for traefik
  file:
    path: "{{ smr_home_dir }}/traefik/acme.json"
    state: touch
    mode: 0600

- name: Copy and decrypt configuration files
  copy:
    src: files/
    dest: "{{ smr_home_dir }}"

- name: Restore backups from s3
  shell: |
    . {{ smr_home_dir }}/.env && docker run --rm \
      -e "ACCESS_KEY=${S3_ACCESS_KEY}" \
      -e "SECRET_KEY=${S3_SECRET_KEY}" \
      -e "S3_PATH=s3://smrealms-backup" \
      -e "PARAMS=--skip-existing" \
      -v {{ smr_home_dir }}/backup/daily:/data/daily:rw \
      -v {{ smr_home_dir }}/backup/archive:/data/archive:rw \
      -v {{ smr_home_dir }}/player-upload:/data/player-upload:rw \
      hemberger/docker-backup-to-s3 get

- name: Fix file permissions for player images
  file:
    path: "{{ smr_home_dir }}/player-upload"
    recurse: yes
    owner: www-data
    group: www-data

- name: Start mysql server to restore database
  shell: docker-compose up --detach mysql
  args:
    chdir: "{{ smr_home_dir }}"

- name: Allow passwordless login to mysql via commandline
  shell: docker-compose exec -T mysql sh -c 'echo "[client]\nhost=localhost\nuser=root\npassword=$MYSQL_ROOT_PASSWORD" > ${HOME}/.my.cnf'
  args:
    chdir: "{{ smr_home_dir }}"

- name: Wait for mysql to start
  pause:
    seconds: 10

- name: Restore database 'smr_live'
  shell: ./restore_smr_live.sh
  args:
    chdir: "{{ smr_home_dir }}/backup"
    creates: "{{ smr_home_dir }}/data/db/smr_live/game.frm"

- name: Restore database 'smr_12_history'
  shell: ./restore_smr_archive.sh smr_12_history.sql.bz2
  args:
    chdir: "{{ smr_home_dir }}/backup"
    creates: "{{ smr_home_dir }}/data/db/smr_12_history/game.frm"

- name: Restore database 'smr_classic_history'
  shell: ./restore_smr_archive.sh smr_classic_history.sql.bz2
  args:
    chdir: "{{ smr_home_dir }}/backup"
    creates: "{{ smr_home_dir }}/data/db/smr_classic_history/game.frm"

- name: Generate MySql password
  set_fact:
    mysql_pass: "{{ lookup('password', '/dev/null chars=ascii_letters,digits length=32') }}"

- name: Put MySql password in config file
  replace:
    path: "{{ smr_home_dir }}/config/SmrMySqlSecrets.inc"
    regexp: "private static \\$password = '.*';"
    replace: "private static $password = '{{ mysql_pass }}';"

- name: Put MySql password in env file
  replace:
    path: "{{ smr_home_dir }}/.env"
    regexp: "MYSQL_PASSWORD=.*"
    replace: "MYSQL_PASSWORD={{ mysql_pass }}"

- name: Generate MySql user 'smr'
  shell: echo "CREATE USER IF NOT EXISTS smr;" | docker exec -i smr-mysql mysql

- name: Set password to MySql user 'smr'
  shell: echo "ALTER USER smr IDENTIFIED BY '{{ mysql_pass }}';" | docker exec -i smr-mysql mysql

- name: Grant permissions to smr_live
  shell: echo "GRANT ALL ON smr_live.* TO smr;" | docker exec -i smr-mysql mysql

- name: Grant permissions to smr_12_history
  shell: echo "GRANT SELECT ON smr_12_history.* TO smr;" | docker exec -i smr-mysql mysql

- name: Grant permissions to smr_classic_history
  shell: echo "GRANT SELECT ON smr_classic_history.* TO smr;" | docker exec -i smr-mysql mysql

- name: Start SMR
  shell: docker-compose up --detach smr
  args:
    chdir: "{{ smr_home_dir }}"

- name: Create cron entry for database backup
  cron:
    name: Database backups
    hour: 9
    minute: 0
    job: cd {{ smr_home_dir }} && nice -n 19 ./backup/backup_cron.sh && docker-compose run --rm backup-s3 no-cron > /dev/null
    disabled: yes

- name: Create cron entry for docker cleanup
  cron:
    name: docker cleanup
    special_time: daily
    job: docker image prune -f > /dev/null
