---
# tasks file for setup-beta

- name: Checkout git repository 'smrealms/smr'
  git:
    repo: git@github.com:smrealms/smr
    dest: "{{ beta_home_dir }}"
    version: master

- name: Copy and decrypt configuration files
  copy:
    src: files/
    dest: "{{ beta_home_dir }}"

- name: Install a cron job to run the npc script
  cron:
    name: Run the beta NPC script
    special_time: hourly
    job: >
        cd {{ beta_home_dir }} &&
        LOGFILE=$(date "+/root/logs/beta_npc_\%Y-\%m-\%d_\%H-\%M-\%S.log") &&
        /usr/local/bin/docker-compose run --rm npc > $LOGFILE 2>&1
